/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n    mutation UserUpdatePasswordWithToken(\n      $password: String!\n      $passwordConfirmation: String!\n      $resetPasswordToken: String!\n    ) {\n      userUpdatePasswordWithToken(\n        password: $password\n        passwordConfirmation: $passwordConfirmation\n        resetPasswordToken: $resetPasswordToken\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  ": types.UserUpdatePasswordWithTokenDocument,
    "\n    mutation userSendPasswordResetWithToken(\n      $email: String!\n      $redirectUrl: String!\n    ) {\n      userSendPasswordResetWithToken(email: $email, redirectUrl: $redirectUrl) {\n        message\n      }\n    }\n  ": types.UserSendPasswordResetWithTokenDocument,
    "\n    mutation UserConfirmRegistrationWithToken($confirmationToken: String!) {\n      userConfirmRegistrationWithToken(\n        confirmationToken: $confirmationToken\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  ": types.UserConfirmRegistrationWithTokenDocument,
    "\n    mutation RegisterUser(\n      $email: String!\n      $password: String!\n      $passwordConfirmation: String!\n      $confirmUrl: String!\n    ) {\n      userRegister(\n        email: $email\n        password: $password\n        passwordConfirmation: $passwordConfirmation\n        confirmUrl: $confirmUrl\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  ": types.RegisterUserDocument,
    "\n    mutation userResendConfirmationWithToken(\n      $email: String!\n      $confirmUrl: String!\n    ) {\n      userResendConfirmationWithToken(email: $email, confirmUrl: $confirmUrl) {\n        message\n      }\n    }\n  ": types.UserResendConfirmationWithTokenDocument,
    "  \n  mutation verticalCog($verticalCog: VerticalCogInput!) {\n    verticalCog(input: $verticalCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n        firstCard {\n          id\n        }\n        firstBlock {\n          id\n        }\n      }\n    }\n  }  \n": types.VerticalCogDocument,
    "\n    mutation duplicateCard($duplicateCard: DuplicateCardInput!) {\n      duplicateCard(input: $duplicateCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n ": types.DuplicateCardDocument,
    "\n    query editorBlock($blockId: ID!) {\n      block(id: $blockId) {\n        id\n        name\n        position\n        cogId\n        cog {\n          id\n          name\n          user {\n            id\n            name\n            email\n            roles\n            photoUrl(width: 1000, height: 1000)\n            organization {\n              id\n              name\n            }\n          }\n        }\n        cards {\n          collection {\n            id\n            blockId\n            parentCardId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n        }\n      }\n    }\n  ": types.EditorBlockDocument,
    "\n    mutation updateCard($updateCard: UpdateCardInput!) {\n      updateCard(input: $updateCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  ": types.UpdateCardDocument,
    "\n    query fetchBlocks {\n      blocks {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          name\n          cogId\n          position\n          cards {\n            metadata {\n              currentPage\n              limitValue\n              totalCount\n              totalPages\n            }\n            collection {\n              id\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 1000, height: 1000)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  ": types.FetchBlocksDocument,
    "\n    mutation changePositionCardSwapper($inputCard: ChangePositionCardInput!) {\n      changePositionCard(input: $inputCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 100, height: 100)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  ": types.ChangePositionCardSwapperDocument,
    "\n    query fetchCogsCardLinks {\n      me {\n        cogs {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n          user {\n            id\n            name\n            email\n            roles\n            photoUrl(width: 1000, height: 1000)\n            organization {\n              id\n              name\n            }\n          }\n          cards {\n            id\n            blockId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n          blocks {\n            collection {\n              id\n              name\n              position\n              cogId\n                cards {\n                  collection {\n                  id\n                  blockId\n                  name\n                  cardType\n                  text\n                  position\n                  photoUrl(width: 1000, height: 1000)\n                  videoUrl\n                  audioUrl\n                  actions\n                }\n              } \n            }\n          }\n        } \n      }\n    }\n  ": types.FetchCogsCardLinksDocument,
    "\n  mutation updateCard($updateCard: UpdateCardInput!) {\n    updateCard(input: $updateCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n": types.UpdateCardDocument,
    "\n    mutation createVerticalCard($inputCard: CreateCardInput!) {\n      createCard(input: $inputCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  ": types.CreateVerticalCardDocument,
    "\n  query editorCog($cogId: ID!) {\n    cog(id: $cogId) {\n      id\n      name\n      user {\n        id\n        name\n        email\n        roles\n        photoUrl(width: 1000, height: 1000)\n        organization {\n          id\n          name\n        }\n      }\n      blocks {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          name\n          cogId\n          position\n          cog {\n            id\n            name\n            user {\n              id\n              name\n              email\n              roles\n              photoUrl(width: 1000, height: 1000)\n              organization {\n                id\n                name\n              }\n            }\n          }\n          cards(page: 1, limit: 100) {\n            metadata {\n              currentPage\n              limitValue\n              totalCount\n              totalPages\n            }\n            collection {\n              id\n              blockId\n              parentCardId\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 300, height: 300)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  }\n": types.EditorCogDocument,
    "\n  mutation createBlock($inputBlock: CreateBlockInput!) {\n    createBlock(input: $inputBlock) {\n      block {\n        id\n        name\n        cogId\n      }\n    }\n  }\n": types.CreateBlockDocument,
    "\n  mutation createCardBlocks($inputCard: CreateCardInput!) {\n    createCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 300, height: 300)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n": types.CreateCardBlocksDocument,
    "\n  mutation updateBlock($updateBlock: UpdateBlockInput!) {\n    updateBlock(input: $updateBlock) {\n      block {\n        id\n        name\n        cards {\n          collection {\n            blockId\n            id\n            cardType\n          }\n        }\n      }\n    }\n  }\n": types.UpdateBlockDocument,
    "\n  mutation updateOpeningCard($updateCard: UpdateCardInput!) {\n    updateCard(input: $updateCard) {\n      card {\n        id\n        name\n      }\n    }\n  }\n": types.UpdateOpeningCardDocument,
    "\n  mutation changePositionCard($inputCard: ChangePositionCardInput!) {\n    changePositionCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 300, height: 300)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n": types.ChangePositionCardDocument,
    "\n  mutation duplicateCard($duplicateCard: DuplicateCardInput!) {\n    duplicateCard(input: $duplicateCard) {\n      card {\n        id\n        blockId\n        parentCardId\n        name\n        cardType\n        text\n        position\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n": types.DuplicateCardDocument,
    "\n  query fetchEditorCog($cogId: ID!, $page: Int) {\n    cog(id: $cogId) {\n      id\n      name\n      user {\n        id\n        name\n        email\n        roles\n        organization {\n          id\n          name\n        }\n      }\n      blocks(page: $page) {\n        collection {\n          id\n          name\n          position\n          cogId\n          cards {\n            collection {\n              id\n              blockId\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 250, height: 250)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  }\n": types.FetchEditorCogDocument,
    "\n  mutation createNewCard($inputCard: CreateCardInput!) {\n    createCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 100, height: 100)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n": types.CreateNewCardDocument,
    "\n  mutation destroyBlock($destroyBlock: DestroyBlockInput!) {\n    destroyBlock(input: $destroyBlock) {\n      id\n      name\n      cogId\n    }\n  }\n": types.DestroyBlockDocument,
    "\n  mutation changePositionBlock($inputBlock: ChangePositionBlockInput!) {\n    changePositionBlock(input: $inputBlock) {\n      block {\n        id\n        name\n        cogId\n        position\n      }\n    }\n  }\n": types.ChangePositionBlockDocument,
    "\n  query communitySearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n    cogsSearch(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n      user: $user\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 250, height: 250)\n        user {\n          id\n          name\n          photoUrl(width: 250, height: 250)\n        }\n      }\n    }\n  }\n": types.CommunitySearchDocument,
    "\n    mutation duplicateBlock($duplicateBlock: DuplicateBlockInput!) {\n      duplicateBlock(input: $duplicateBlock) {\n        block {\n          id\n          name\n          cogId\n        }\n      }\n    }\n ": types.DuplicateBlockDocument,
    "\n  mutation duplicateCog($duplicateCog: DuplicateCogInput!) {\n    duplicateCog(input: $duplicateCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n        firstCard {\n          id\n        }\n        firstBlock {\n          id         \n        }   \n      }\n    }\n  }\n": types.DuplicateCogDocument,
    "\n  mutation pinCog($updateCog: UpdateCogInput!) {\n    updateCog(input: $updateCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n      }\n    }\n  }\n": types.PinCogDocument,
    "\n  mutation destroyCog($destroyCog: DestroyCogInput!) {\n    destroyCog(input: $destroyCog) {\n      id\n      name\n      description\n      tags\n      isPinned\n      isPublic\n      createdAt\n      photoUrl(width: 1000, height: 1000)\n    }\n  }\n": types.DestroyCogDocument,
    "\n  query libraryBlockSearch($pagination: JSON, $filters: JSON, $order: String) {\n    blocksSearch(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        createdAt\n        cogId\n        cog {\n          id\n          name\n        }\n        cards(page: 1, limit: 6) {\n          metadata {\n            currentPage\n            limitValue\n            totalCount\n            totalPages\n          }\n          collection {\n            id\n            blockId\n            parentCardId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n        }\n      }\n    }\n  }\n": types.LibraryBlockSearchDocument,
    "\n  query cardsSearch($pagination: JSON, $filters: JSON, $order: String) {\n    cardsSearch(pagination: $pagination, filters: $filters, order: $order) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        cardType\n        text\n        createdAt\n        blockId\n        audioUrl\n        videoUrl\n        photoUrl(width: 1000, height: 1000)\n        block {\n          id\n          name\n          cogId\n        }\n      }\n    }\n  }\n": types.CardsSearchDocument,
    "\n  query libraryCogSearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n  cogsMine(\n    pagination: $pagination\n    filters: $filters\n    order: $order\n    user: $user\n  ) {\n    metadata {\n      currentPage\n      limitValue\n      totalCount\n      totalPages\n    }\n    collection {\n      id\n      name\n      description\n      tags\n      isPinned\n      isPublic\n      createdAt\n      photoUrl(width: 250, height: 250)\n      user {\n        id\n        name\n        email\n        roles\n        photoUrl(width: 1000, height: 1000)\n        organization {\n          id\n          name\n        }\n      }\n    }\n  }\n}\n": types.LibraryCogSearchDocument,
    "\n  query fetchCogsEditor {\n    me {\n      cogs {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n      } \n    }\n  }\n": types.FetchCogsEditorDocument,
    "\n    mutation createCog($inputCog: CreateCogInput!) {\n      createCog(input: $inputCog) {\n        cog {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n        }\n      }\n    }\n  ": types.CreateCogDocument,
    "\n    mutation updateCog($updateCog: UpdateCogInput!) {\n      updateCog(input: $updateCog) {\n        cog {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n        }\n      }\n    }\n  ": types.UpdateCogDocument,
    "\n  mutation llmGenerateCog($inputCog: LlmGenerateCogInput!) {\n    llmGenerateCog(input: $inputCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n      }\n    }\n  }\n": types.LlmGenerateCogDocument,
    "\n  query libraryModalCogSearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n    cogsMine(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n      user: $user\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 250, height: 250)\n        user {\n          id\n          name\n          photoUrl(width: 250, height: 250)\n        }\n        blocks {\n          collection {\n            id\n            name\n            position\n            createdAt\n            cards {\n              collection {\n                id\n                blockId\n                name\n                cardType\n                text\n                position\n                photoUrl\n                videoUrl\n                audioUrl\n                actions\n              }          \n            }\n          }    \n        }\n      }\n    }\n  }\n": types.LibraryModalCogSearchDocument,
    "\n  query block($blockId: ID!) {\n    block(id: $blockId) {\n      id\n      name\n      position\n      cogId\n      cog {\n        id\n        name\n        user {\n          id\n          name\n          email\n          roles\n          photoUrl(width: 1000, height: 1000)\n          organization {\n            id\n            name\n          }\n        }\n      }\n      cards(page: 1, limit: 100) {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  }\n": types.BlockDocument,
    "\n    mutation destroyCard($destroyCard: DestroyCardInput!) {\n      destroyCard(input: $destroyCard) {\n        id\n        name\n        blockId\n      }\n    }\n  ": types.DestroyCardDocument,
    "\n    mutation changePositionCardEditor($inputCard: ChangePositionCardInput!) {\n      changePositionCard(input: $inputCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  ": types.ChangePositionCardEditorDocument,
    "\n    mutation createCard($inputCard: CreateCardInput!) {\n      createCard(input: $inputCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  ": types.CreateCardDocument,
    "\n  mutation llmGenerateCard($inputCard: LlmGenerateCardInput!) {\n    llmGenerateCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n  ": types.LlmGenerateCardDocument,
    "\n  mutation llmGenerateImage($input: LlmGenerateImageInput!) {\n    llmGenerateImage(input: $input) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n  ": types.LlmGenerateImageDocument,
    "\n    query fetchCogView($cogId: ID!) {\n      cog(id: $cogId) {\n        id\n        name\n        user {\n          id\n          name\n          email\n          roles\n          photoUrl\n          organization {\n            id\n            name\n          }\n        }\n        cards {\n          id\n          cardType\n          actions\n        }\n        blocks {\n          collection {\n            id\n            name\n            position\n            cogId\n            cards(page: 1, limit: 100) {\n              metadata {\n                currentPage\n                limitValue\n                totalCount\n                totalPages\n              }\n              collection {\n                id\n                blockId\n                parentCardId\n                name\n                cardType\n                text\n                position\n                photoUrl\n                videoUrl\n                audioUrl\n                actions\n                block {\n                  cogId\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": types.FetchCogViewDocument,
    "\n    mutation saveCog($duplicateCog: DuplicateCogInput!) {\n      duplicateCog(input: $duplicateCog) {\n        cog {\n          id\n          name\n        }\n      }\n    }\n ": types.SaveCogDocument,
    "\n  query fetchMe {\n    me {\n      id\n      name\n      bio\n      email\n      roles\n      photoUrl(width: 1000, height: 1000)\n      organization {\n        id\n        name\n      }\n    }\n  }\n": types.FetchMeDocument,
    "\n  mutation updateUser($updateUser: UpdateUserInput!) {\n    updateUser(input: $updateUser) {\n      user {\n        id\n        name\n        bio\n        photoUrl(width: 1000, height: 1000)\n      }\n    }\n  }\n": types.UpdateUserDocument,
    "\n  query user($userId: ID!) {\n    user(id: $userId) {\n      id\n      name\n      bio\n      email\n      roles\n      photoUrl(width: 1000, height: 1000)\n      organization {\n        id \n        name\n        photoUrl\n      }\n      cogs {\n        id\n        name\n        description\n        photoUrl(width: 1000, height: 1000)\n        tags\n        isPinned\n        isPublic\n        createdAt\n      }\n    }\n  }\n": types.UserDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UserUpdatePasswordWithToken(\n      $password: String!\n      $passwordConfirmation: String!\n      $resetPasswordToken: String!\n    ) {\n      userUpdatePasswordWithToken(\n        password: $password\n        passwordConfirmation: $passwordConfirmation\n        resetPasswordToken: $resetPasswordToken\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation UserUpdatePasswordWithToken(\n      $password: String!\n      $passwordConfirmation: String!\n      $resetPasswordToken: String!\n    ) {\n      userUpdatePasswordWithToken(\n        password: $password\n        passwordConfirmation: $passwordConfirmation\n        resetPasswordToken: $resetPasswordToken\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation userSendPasswordResetWithToken(\n      $email: String!\n      $redirectUrl: String!\n    ) {\n      userSendPasswordResetWithToken(email: $email, redirectUrl: $redirectUrl) {\n        message\n      }\n    }\n  "): (typeof documents)["\n    mutation userSendPasswordResetWithToken(\n      $email: String!\n      $redirectUrl: String!\n    ) {\n      userSendPasswordResetWithToken(email: $email, redirectUrl: $redirectUrl) {\n        message\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UserConfirmRegistrationWithToken($confirmationToken: String!) {\n      userConfirmRegistrationWithToken(\n        confirmationToken: $confirmationToken\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation UserConfirmRegistrationWithToken($confirmationToken: String!) {\n      userConfirmRegistrationWithToken(\n        confirmationToken: $confirmationToken\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation RegisterUser(\n      $email: String!\n      $password: String!\n      $passwordConfirmation: String!\n      $confirmUrl: String!\n    ) {\n      userRegister(\n        email: $email\n        password: $password\n        passwordConfirmation: $passwordConfirmation\n        confirmUrl: $confirmUrl\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation RegisterUser(\n      $email: String!\n      $password: String!\n      $passwordConfirmation: String!\n      $confirmUrl: String!\n    ) {\n      userRegister(\n        email: $email\n        password: $password\n        passwordConfirmation: $passwordConfirmation\n        confirmUrl: $confirmUrl\n      ) {\n        credentials {\n          accessToken\n          expiry\n          tokenType\n          client\n          uid\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation userResendConfirmationWithToken(\n      $email: String!\n      $confirmUrl: String!\n    ) {\n      userResendConfirmationWithToken(email: $email, confirmUrl: $confirmUrl) {\n        message\n      }\n    }\n  "): (typeof documents)["\n    mutation userResendConfirmationWithToken(\n      $email: String!\n      $confirmUrl: String!\n    ) {\n      userResendConfirmationWithToken(email: $email, confirmUrl: $confirmUrl) {\n        message\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "  \n  mutation verticalCog($verticalCog: VerticalCogInput!) {\n    verticalCog(input: $verticalCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n        firstCard {\n          id\n        }\n        firstBlock {\n          id\n        }\n      }\n    }\n  }  \n"): (typeof documents)["  \n  mutation verticalCog($verticalCog: VerticalCogInput!) {\n    verticalCog(input: $verticalCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n        firstCard {\n          id\n        }\n        firstBlock {\n          id\n        }\n      }\n    }\n  }  \n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation duplicateCard($duplicateCard: DuplicateCardInput!) {\n      duplicateCard(input: $duplicateCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n "): (typeof documents)["\n    mutation duplicateCard($duplicateCard: DuplicateCardInput!) {\n      duplicateCard(input: $duplicateCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query editorBlock($blockId: ID!) {\n      block(id: $blockId) {\n        id\n        name\n        position\n        cogId\n        cog {\n          id\n          name\n          user {\n            id\n            name\n            email\n            roles\n            photoUrl(width: 1000, height: 1000)\n            organization {\n              id\n              name\n            }\n          }\n        }\n        cards {\n          collection {\n            id\n            blockId\n            parentCardId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n        }\n      }\n    }\n  "): (typeof documents)["\n    query editorBlock($blockId: ID!) {\n      block(id: $blockId) {\n        id\n        name\n        position\n        cogId\n        cog {\n          id\n          name\n          user {\n            id\n            name\n            email\n            roles\n            photoUrl(width: 1000, height: 1000)\n            organization {\n              id\n              name\n            }\n          }\n        }\n        cards {\n          collection {\n            id\n            blockId\n            parentCardId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation updateCard($updateCard: UpdateCardInput!) {\n      updateCard(input: $updateCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation updateCard($updateCard: UpdateCardInput!) {\n      updateCard(input: $updateCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query fetchBlocks {\n      blocks {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          name\n          cogId\n          position\n          cards {\n            metadata {\n              currentPage\n              limitValue\n              totalCount\n              totalPages\n            }\n            collection {\n              id\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 1000, height: 1000)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  "): (typeof documents)["\n    query fetchBlocks {\n      blocks {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          name\n          cogId\n          position\n          cards {\n            metadata {\n              currentPage\n              limitValue\n              totalCount\n              totalPages\n            }\n            collection {\n              id\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 1000, height: 1000)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation changePositionCardSwapper($inputCard: ChangePositionCardInput!) {\n      changePositionCard(input: $inputCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 100, height: 100)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation changePositionCardSwapper($inputCard: ChangePositionCardInput!) {\n      changePositionCard(input: $inputCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 100, height: 100)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query fetchCogsCardLinks {\n      me {\n        cogs {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n          user {\n            id\n            name\n            email\n            roles\n            photoUrl(width: 1000, height: 1000)\n            organization {\n              id\n              name\n            }\n          }\n          cards {\n            id\n            blockId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n          blocks {\n            collection {\n              id\n              name\n              position\n              cogId\n                cards {\n                  collection {\n                  id\n                  blockId\n                  name\n                  cardType\n                  text\n                  position\n                  photoUrl(width: 1000, height: 1000)\n                  videoUrl\n                  audioUrl\n                  actions\n                }\n              } \n            }\n          }\n        } \n      }\n    }\n  "): (typeof documents)["\n    query fetchCogsCardLinks {\n      me {\n        cogs {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n          user {\n            id\n            name\n            email\n            roles\n            photoUrl(width: 1000, height: 1000)\n            organization {\n              id\n              name\n            }\n          }\n          cards {\n            id\n            blockId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n          blocks {\n            collection {\n              id\n              name\n              position\n              cogId\n                cards {\n                  collection {\n                  id\n                  blockId\n                  name\n                  cardType\n                  text\n                  position\n                  photoUrl(width: 1000, height: 1000)\n                  videoUrl\n                  audioUrl\n                  actions\n                }\n              } \n            }\n          }\n        } \n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation updateCard($updateCard: UpdateCardInput!) {\n    updateCard(input: $updateCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateCard($updateCard: UpdateCardInput!) {\n    updateCard(input: $updateCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation createVerticalCard($inputCard: CreateCardInput!) {\n      createCard(input: $inputCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation createVerticalCard($inputCard: CreateCardInput!) {\n      createCard(input: $inputCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query editorCog($cogId: ID!) {\n    cog(id: $cogId) {\n      id\n      name\n      user {\n        id\n        name\n        email\n        roles\n        photoUrl(width: 1000, height: 1000)\n        organization {\n          id\n          name\n        }\n      }\n      blocks {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          name\n          cogId\n          position\n          cog {\n            id\n            name\n            user {\n              id\n              name\n              email\n              roles\n              photoUrl(width: 1000, height: 1000)\n              organization {\n                id\n                name\n              }\n            }\n          }\n          cards(page: 1, limit: 100) {\n            metadata {\n              currentPage\n              limitValue\n              totalCount\n              totalPages\n            }\n            collection {\n              id\n              blockId\n              parentCardId\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 300, height: 300)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query editorCog($cogId: ID!) {\n    cog(id: $cogId) {\n      id\n      name\n      user {\n        id\n        name\n        email\n        roles\n        photoUrl(width: 1000, height: 1000)\n        organization {\n          id\n          name\n        }\n      }\n      blocks {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          name\n          cogId\n          position\n          cog {\n            id\n            name\n            user {\n              id\n              name\n              email\n              roles\n              photoUrl(width: 1000, height: 1000)\n              organization {\n                id\n                name\n              }\n            }\n          }\n          cards(page: 1, limit: 100) {\n            metadata {\n              currentPage\n              limitValue\n              totalCount\n              totalPages\n            }\n            collection {\n              id\n              blockId\n              parentCardId\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 300, height: 300)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation createBlock($inputBlock: CreateBlockInput!) {\n    createBlock(input: $inputBlock) {\n      block {\n        id\n        name\n        cogId\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createBlock($inputBlock: CreateBlockInput!) {\n    createBlock(input: $inputBlock) {\n      block {\n        id\n        name\n        cogId\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation createCardBlocks($inputCard: CreateCardInput!) {\n    createCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 300, height: 300)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createCardBlocks($inputCard: CreateCardInput!) {\n    createCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 300, height: 300)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation updateBlock($updateBlock: UpdateBlockInput!) {\n    updateBlock(input: $updateBlock) {\n      block {\n        id\n        name\n        cards {\n          collection {\n            blockId\n            id\n            cardType\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateBlock($updateBlock: UpdateBlockInput!) {\n    updateBlock(input: $updateBlock) {\n      block {\n        id\n        name\n        cards {\n          collection {\n            blockId\n            id\n            cardType\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation updateOpeningCard($updateCard: UpdateCardInput!) {\n    updateCard(input: $updateCard) {\n      card {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateOpeningCard($updateCard: UpdateCardInput!) {\n    updateCard(input: $updateCard) {\n      card {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation changePositionCard($inputCard: ChangePositionCardInput!) {\n    changePositionCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 300, height: 300)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation changePositionCard($inputCard: ChangePositionCardInput!) {\n    changePositionCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 300, height: 300)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation duplicateCard($duplicateCard: DuplicateCardInput!) {\n    duplicateCard(input: $duplicateCard) {\n      card {\n        id\n        blockId\n        parentCardId\n        name\n        cardType\n        text\n        position\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation duplicateCard($duplicateCard: DuplicateCardInput!) {\n    duplicateCard(input: $duplicateCard) {\n      card {\n        id\n        blockId\n        parentCardId\n        name\n        cardType\n        text\n        position\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query fetchEditorCog($cogId: ID!, $page: Int) {\n    cog(id: $cogId) {\n      id\n      name\n      user {\n        id\n        name\n        email\n        roles\n        organization {\n          id\n          name\n        }\n      }\n      blocks(page: $page) {\n        collection {\n          id\n          name\n          position\n          cogId\n          cards {\n            collection {\n              id\n              blockId\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 250, height: 250)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchEditorCog($cogId: ID!, $page: Int) {\n    cog(id: $cogId) {\n      id\n      name\n      user {\n        id\n        name\n        email\n        roles\n        organization {\n          id\n          name\n        }\n      }\n      blocks(page: $page) {\n        collection {\n          id\n          name\n          position\n          cogId\n          cards {\n            collection {\n              id\n              blockId\n              name\n              cardType\n              text\n              position\n              photoUrl(width: 250, height: 250)\n              videoUrl\n              audioUrl\n              actions\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation createNewCard($inputCard: CreateCardInput!) {\n    createCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 100, height: 100)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createNewCard($inputCard: CreateCardInput!) {\n    createCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 100, height: 100)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation destroyBlock($destroyBlock: DestroyBlockInput!) {\n    destroyBlock(input: $destroyBlock) {\n      id\n      name\n      cogId\n    }\n  }\n"): (typeof documents)["\n  mutation destroyBlock($destroyBlock: DestroyBlockInput!) {\n    destroyBlock(input: $destroyBlock) {\n      id\n      name\n      cogId\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation changePositionBlock($inputBlock: ChangePositionBlockInput!) {\n    changePositionBlock(input: $inputBlock) {\n      block {\n        id\n        name\n        cogId\n        position\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation changePositionBlock($inputBlock: ChangePositionBlockInput!) {\n    changePositionBlock(input: $inputBlock) {\n      block {\n        id\n        name\n        cogId\n        position\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query communitySearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n    cogsSearch(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n      user: $user\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 250, height: 250)\n        user {\n          id\n          name\n          photoUrl(width: 250, height: 250)\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query communitySearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n    cogsSearch(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n      user: $user\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 250, height: 250)\n        user {\n          id\n          name\n          photoUrl(width: 250, height: 250)\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation duplicateBlock($duplicateBlock: DuplicateBlockInput!) {\n      duplicateBlock(input: $duplicateBlock) {\n        block {\n          id\n          name\n          cogId\n        }\n      }\n    }\n "): (typeof documents)["\n    mutation duplicateBlock($duplicateBlock: DuplicateBlockInput!) {\n      duplicateBlock(input: $duplicateBlock) {\n        block {\n          id\n          name\n          cogId\n        }\n      }\n    }\n "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation duplicateCog($duplicateCog: DuplicateCogInput!) {\n    duplicateCog(input: $duplicateCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n        firstCard {\n          id\n        }\n        firstBlock {\n          id         \n        }   \n      }\n    }\n  }\n"): (typeof documents)["\n  mutation duplicateCog($duplicateCog: DuplicateCogInput!) {\n    duplicateCog(input: $duplicateCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n        firstCard {\n          id\n        }\n        firstBlock {\n          id         \n        }   \n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation pinCog($updateCog: UpdateCogInput!) {\n    updateCog(input: $updateCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation pinCog($updateCog: UpdateCogInput!) {\n    updateCog(input: $updateCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation destroyCog($destroyCog: DestroyCogInput!) {\n    destroyCog(input: $destroyCog) {\n      id\n      name\n      description\n      tags\n      isPinned\n      isPublic\n      createdAt\n      photoUrl(width: 1000, height: 1000)\n    }\n  }\n"): (typeof documents)["\n  mutation destroyCog($destroyCog: DestroyCogInput!) {\n    destroyCog(input: $destroyCog) {\n      id\n      name\n      description\n      tags\n      isPinned\n      isPublic\n      createdAt\n      photoUrl(width: 1000, height: 1000)\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query libraryBlockSearch($pagination: JSON, $filters: JSON, $order: String) {\n    blocksSearch(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        createdAt\n        cogId\n        cog {\n          id\n          name\n        }\n        cards(page: 1, limit: 6) {\n          metadata {\n            currentPage\n            limitValue\n            totalCount\n            totalPages\n          }\n          collection {\n            id\n            blockId\n            parentCardId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query libraryBlockSearch($pagination: JSON, $filters: JSON, $order: String) {\n    blocksSearch(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        createdAt\n        cogId\n        cog {\n          id\n          name\n        }\n        cards(page: 1, limit: 6) {\n          metadata {\n            currentPage\n            limitValue\n            totalCount\n            totalPages\n          }\n          collection {\n            id\n            blockId\n            parentCardId\n            name\n            cardType\n            text\n            position\n            photoUrl(width: 1000, height: 1000)\n            videoUrl\n            audioUrl\n            actions\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query cardsSearch($pagination: JSON, $filters: JSON, $order: String) {\n    cardsSearch(pagination: $pagination, filters: $filters, order: $order) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        cardType\n        text\n        createdAt\n        blockId\n        audioUrl\n        videoUrl\n        photoUrl(width: 1000, height: 1000)\n        block {\n          id\n          name\n          cogId\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query cardsSearch($pagination: JSON, $filters: JSON, $order: String) {\n    cardsSearch(pagination: $pagination, filters: $filters, order: $order) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        cardType\n        text\n        createdAt\n        blockId\n        audioUrl\n        videoUrl\n        photoUrl(width: 1000, height: 1000)\n        block {\n          id\n          name\n          cogId\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query libraryCogSearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n  cogsMine(\n    pagination: $pagination\n    filters: $filters\n    order: $order\n    user: $user\n  ) {\n    metadata {\n      currentPage\n      limitValue\n      totalCount\n      totalPages\n    }\n    collection {\n      id\n      name\n      description\n      tags\n      isPinned\n      isPublic\n      createdAt\n      photoUrl(width: 250, height: 250)\n      user {\n        id\n        name\n        email\n        roles\n        photoUrl(width: 1000, height: 1000)\n        organization {\n          id\n          name\n        }\n      }\n    }\n  }\n}\n"): (typeof documents)["\n  query libraryCogSearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n  cogsMine(\n    pagination: $pagination\n    filters: $filters\n    order: $order\n    user: $user\n  ) {\n    metadata {\n      currentPage\n      limitValue\n      totalCount\n      totalPages\n    }\n    collection {\n      id\n      name\n      description\n      tags\n      isPinned\n      isPublic\n      createdAt\n      photoUrl(width: 250, height: 250)\n      user {\n        id\n        name\n        email\n        roles\n        photoUrl(width: 1000, height: 1000)\n        organization {\n          id\n          name\n        }\n      }\n    }\n  }\n}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query fetchCogsEditor {\n    me {\n      cogs {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n      } \n    }\n  }\n"): (typeof documents)["\n  query fetchCogsEditor {\n    me {\n      cogs {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 1000, height: 1000)\n      } \n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation createCog($inputCog: CreateCogInput!) {\n      createCog(input: $inputCog) {\n        cog {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation createCog($inputCog: CreateCogInput!) {\n      createCog(input: $inputCog) {\n        cog {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation updateCog($updateCog: UpdateCogInput!) {\n      updateCog(input: $updateCog) {\n        cog {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation updateCog($updateCog: UpdateCogInput!) {\n      updateCog(input: $updateCog) {\n        cog {\n          id\n          name\n          description\n          tags\n          isPinned\n          isPublic\n          createdAt\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation llmGenerateCog($inputCog: LlmGenerateCogInput!) {\n    llmGenerateCog(input: $inputCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation llmGenerateCog($inputCog: LlmGenerateCogInput!) {\n    llmGenerateCog(input: $inputCog) {\n      cog {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query libraryModalCogSearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n    cogsMine(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n      user: $user\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 250, height: 250)\n        user {\n          id\n          name\n          photoUrl(width: 250, height: 250)\n        }\n        blocks {\n          collection {\n            id\n            name\n            position\n            createdAt\n            cards {\n              collection {\n                id\n                blockId\n                name\n                cardType\n                text\n                position\n                photoUrl\n                videoUrl\n                audioUrl\n                actions\n              }          \n            }\n          }    \n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query libraryModalCogSearch($pagination: JSON, $filters: JSON, $order: String, $user: UserEnum) {\n    cogsMine(\n      pagination: $pagination\n      filters: $filters\n      order: $order\n      user: $user\n    ) {\n      metadata {\n        currentPage\n        limitValue\n        totalCount\n        totalPages\n      }\n      collection {\n        id\n        name\n        description\n        tags\n        isPinned\n        isPublic\n        createdAt\n        photoUrl(width: 250, height: 250)\n        user {\n          id\n          name\n          photoUrl(width: 250, height: 250)\n        }\n        blocks {\n          collection {\n            id\n            name\n            position\n            createdAt\n            cards {\n              collection {\n                id\n                blockId\n                name\n                cardType\n                text\n                position\n                photoUrl\n                videoUrl\n                audioUrl\n                actions\n              }          \n            }\n          }    \n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query block($blockId: ID!) {\n    block(id: $blockId) {\n      id\n      name\n      position\n      cogId\n      cog {\n        id\n        name\n        user {\n          id\n          name\n          email\n          roles\n          photoUrl(width: 1000, height: 1000)\n          organization {\n            id\n            name\n          }\n        }\n      }\n      cards(page: 1, limit: 100) {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query block($blockId: ID!) {\n    block(id: $blockId) {\n      id\n      name\n      position\n      cogId\n      cog {\n        id\n        name\n        user {\n          id\n          name\n          email\n          roles\n          photoUrl(width: 1000, height: 1000)\n          organization {\n            id\n            name\n          }\n        }\n      }\n      cards(page: 1, limit: 100) {\n        metadata {\n          currentPage\n          limitValue\n          totalCount\n          totalPages\n        }\n        collection {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation destroyCard($destroyCard: DestroyCardInput!) {\n      destroyCard(input: $destroyCard) {\n        id\n        name\n        blockId\n      }\n    }\n  "): (typeof documents)["\n    mutation destroyCard($destroyCard: DestroyCardInput!) {\n      destroyCard(input: $destroyCard) {\n        id\n        name\n        blockId\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation changePositionCardEditor($inputCard: ChangePositionCardInput!) {\n      changePositionCard(input: $inputCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation changePositionCardEditor($inputCard: ChangePositionCardInput!) {\n      changePositionCard(input: $inputCard) {\n        card {\n          id\n          name\n          blockId\n          cardType\n          text\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation createCard($inputCard: CreateCardInput!) {\n      createCard(input: $inputCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "): (typeof documents)["\n    mutation createCard($inputCard: CreateCardInput!) {\n      createCard(input: $inputCard) {\n        card {\n          id\n          blockId\n          parentCardId\n          name\n          cardType\n          text\n          position\n          photoUrl(width: 1000, height: 1000)\n          videoUrl\n          audioUrl\n          actions\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation llmGenerateCard($inputCard: LlmGenerateCardInput!) {\n    llmGenerateCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n  "): (typeof documents)["\n  mutation llmGenerateCard($inputCard: LlmGenerateCardInput!) {\n    llmGenerateCard(input: $inputCard) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation llmGenerateImage($input: LlmGenerateImageInput!) {\n    llmGenerateImage(input: $input) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n  "): (typeof documents)["\n  mutation llmGenerateImage($input: LlmGenerateImageInput!) {\n    llmGenerateImage(input: $input) {\n      card {\n        id\n        name\n        blockId\n        cardType\n        text\n        photoUrl(width: 1000, height: 1000)\n        videoUrl\n        audioUrl\n        actions\n      }\n    }\n  }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query fetchCogView($cogId: ID!) {\n      cog(id: $cogId) {\n        id\n        name\n        user {\n          id\n          name\n          email\n          roles\n          photoUrl\n          organization {\n            id\n            name\n          }\n        }\n        cards {\n          id\n          cardType\n          actions\n        }\n        blocks {\n          collection {\n            id\n            name\n            position\n            cogId\n            cards(page: 1, limit: 100) {\n              metadata {\n                currentPage\n                limitValue\n                totalCount\n                totalPages\n              }\n              collection {\n                id\n                blockId\n                parentCardId\n                name\n                cardType\n                text\n                position\n                photoUrl\n                videoUrl\n                audioUrl\n                actions\n                block {\n                  cogId\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  "): (typeof documents)["\n    query fetchCogView($cogId: ID!) {\n      cog(id: $cogId) {\n        id\n        name\n        user {\n          id\n          name\n          email\n          roles\n          photoUrl\n          organization {\n            id\n            name\n          }\n        }\n        cards {\n          id\n          cardType\n          actions\n        }\n        blocks {\n          collection {\n            id\n            name\n            position\n            cogId\n            cards(page: 1, limit: 100) {\n              metadata {\n                currentPage\n                limitValue\n                totalCount\n                totalPages\n              }\n              collection {\n                id\n                blockId\n                parentCardId\n                name\n                cardType\n                text\n                position\n                photoUrl\n                videoUrl\n                audioUrl\n                actions\n                block {\n                  cogId\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation saveCog($duplicateCog: DuplicateCogInput!) {\n      duplicateCog(input: $duplicateCog) {\n        cog {\n          id\n          name\n        }\n      }\n    }\n "): (typeof documents)["\n    mutation saveCog($duplicateCog: DuplicateCogInput!) {\n      duplicateCog(input: $duplicateCog) {\n        cog {\n          id\n          name\n        }\n      }\n    }\n "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query fetchMe {\n    me {\n      id\n      name\n      bio\n      email\n      roles\n      photoUrl(width: 1000, height: 1000)\n      organization {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchMe {\n    me {\n      id\n      name\n      bio\n      email\n      roles\n      photoUrl(width: 1000, height: 1000)\n      organization {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation updateUser($updateUser: UpdateUserInput!) {\n    updateUser(input: $updateUser) {\n      user {\n        id\n        name\n        bio\n        photoUrl(width: 1000, height: 1000)\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateUser($updateUser: UpdateUserInput!) {\n    updateUser(input: $updateUser) {\n      user {\n        id\n        name\n        bio\n        photoUrl(width: 1000, height: 1000)\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query user($userId: ID!) {\n    user(id: $userId) {\n      id\n      name\n      bio\n      email\n      roles\n      photoUrl(width: 1000, height: 1000)\n      organization {\n        id \n        name\n        photoUrl\n      }\n      cogs {\n        id\n        name\n        description\n        photoUrl(width: 1000, height: 1000)\n        tags\n        isPinned\n        isPublic\n        createdAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query user($userId: ID!) {\n    user(id: $userId) {\n      id\n      name\n      bio\n      email\n      roles\n      photoUrl(width: 1000, height: 1000)\n      organization {\n        id \n        name\n        photoUrl\n      }\n      cogs {\n        id\n        name\n        description\n        photoUrl(width: 1000, height: 1000)\n        tags\n        isPinned\n        isPublic\n        createdAt\n      }\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;